export const AIRCRAFT_REQUEST = "ADD_AIRCRAFT_REQUEST";
export const AIRCRAFT_FAILURE = "ADD_AIRCRAFT_FAILURE";

// POST
export const ADD_AIRCRAFT_SUCCESS = "ADD_AIRCRAFT_SUCCESS";

export const GET_AIRCRAFT_SUCCESS = "GET_AIRCRAFT_SUCCESS";