export const BID_REQUEST = "ADD_BID_REQUEST";
export const BID_FAILURE = "ADD_BID_FAILURE";

// POST
export const ADD_BID_SUCCESS = "ADD_BID_SUCCESS";

export const GET_BID_SUCCESS = "GET_BID_SUCCESS";

export const PAYMENT_CONFIRMATION_SUCCESS = "PAYMENT_CONFIRMATION_SUCCESS";